# Visualizacion de unas pocas historias (requiere compilar con UI/Vis).
/control/verbose 1
/run/verbose 1
/testem/det/setMat G4_Al
/testem/det/setSize 3 cm
/run/initialize
/process/inactivate phot
/process/inactivate conv
/process/inactivate GammaToMuPair
/gun/particle gamma
/gun/energy 300 keV
/vis/open
/vis/drawVolume
/vis/viewer/set/style wireframe
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/scene/endOfEventAction accumulate
/run/beamOn 10
