# VRML2 headless: transmisión y dispersión Compton en aluminio (10 eventos).
/control/verbose 1
/run/verbose 1
/random/setSeeds 10101 10102
/testem/det/setMat G4_Al
/testem/det/setSize 2 cm
/run/initialize
/process/inactivate phot
/process/inactivate conv
/process/inactivate GammaToMuPair
/gun/particle gamma
/gun/energy 300 keV
/vis/open VRML2FILE
/vis/viewer/set/autoRefresh false
/vis/drawVolume
/tracking/storeTrajectory 1
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/scene/endOfEventAction accumulate
/run/beamOn 10
/vis/viewer/flush
