# VRML2 headless: mu+ de 3 GeV a través de 100 cm de agua (10 eventos).
/control/verbose 1
/run/verbose 1
/random/setSeeds 10401 10402
/testem/det/setMat G4_WATER
/testem/det/setSize 100 cm
/testem/phys/addPhysics standard
/run/setCut 1 mm
/run/initialize
/gun/particle mu+
/gun/energy 3 GeV
/testem/trackSecondaries true
/tracking/storeTrajectory 1
/vis/open VRML2FILE
/vis/viewer/set/autoRefresh false
/vis/drawVolume
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/scene/endOfEventAction accumulate
/run/beamOn 10
/vis/viewer/flush
