# Experimento 1B: 200000 primeras interacciones Compton.
/control/verbose 1
/run/verbose 1
/testem/det/setMat G4_Al
/testem/phys/addPhysics standard
/run/initialize
/run/setCut 1 nm
/process/inactivate phot
/process/inactivate conv
/process/inactivate GammaToMuPair
/particle/select gamma
/particle/process/dump
/gun/particle gamma
/gun/energy 300 keV
/random/setSeeds 97531 86420
/run/beamOn 200000
